-- Store LeetCode topic tags as slugs instead of display names.
-- Slugs survive LeetCode renames ("Graph" -> "Graph Theory" is still `graph`);
-- names now come from packages/core/src/leetcode-tags.ts at render time.
-- Unknown names fall back to a lowercase-hyphen slug, matching leetcodeTagSlug().
UPDATE `problems`
SET `topic_tags` = (
	SELECT json_group_array(DISTINCT CASE lower(trim(`value`))
		WHEN 'array' THEN 'array'
		WHEN 'string' THEN 'string'
		WHEN 'two pointers' THEN 'two-pointers'
		WHEN 'two-pointers' THEN 'two-pointers'
		WHEN 'sorting' THEN 'sorting'
		WHEN 'stack' THEN 'stack'
		WHEN 'queue' THEN 'queue'
		WHEN 'linked list' THEN 'linked-list'
		WHEN 'linked-list' THEN 'linked-list'
		WHEN 'matrix' THEN 'matrix'
		WHEN 'simulation' THEN 'simulation'
		WHEN 'enumeration' THEN 'enumeration'
		WHEN 'counting' THEN 'counting'
		WHEN 'hash table' THEN 'hash-table'
		WHEN 'hash-table' THEN 'hash-table'
		WHEN 'math' THEN 'math'
		WHEN 'binary search' THEN 'binary-search'
		WHEN 'binary-search' THEN 'binary-search'
		WHEN 'sliding window' THEN 'sliding-window'
		WHEN 'sliding-window' THEN 'sliding-window'
		WHEN 'prefix sum' THEN 'prefix-sum'
		WHEN 'prefix-sum' THEN 'prefix-sum'
		WHEN 'greedy' THEN 'greedy'
		WHEN 'heap (priority queue)' THEN 'heap-priority-queue'
		WHEN 'heap-priority-queue' THEN 'heap-priority-queue'
		WHEN 'tree' THEN 'tree'
		WHEN 'binary tree' THEN 'binary-tree'
		WHEN 'binary-tree' THEN 'binary-tree'
		WHEN 'binary search tree' THEN 'binary-search-tree'
		WHEN 'binary-search-tree' THEN 'binary-search-tree'
		WHEN 'depth-first search' THEN 'depth-first-search'
		WHEN 'depth-first-search' THEN 'depth-first-search'
		WHEN 'breadth-first search' THEN 'breadth-first-search'
		WHEN 'breadth-first-search' THEN 'breadth-first-search'
		WHEN 'graph theory' THEN 'graph'
		WHEN 'graph' THEN 'graph'
		WHEN 'recursion' THEN 'recursion'
		WHEN 'bit manipulation' THEN 'bit-manipulation'
		WHEN 'bit-manipulation' THEN 'bit-manipulation'
		WHEN 'design' THEN 'design'
		WHEN 'doubly-linked list' THEN 'doubly-linked-list'
		WHEN 'doubly-linked-list' THEN 'doubly-linked-list'
		WHEN 'ordered set' THEN 'ordered-set'
		WHEN 'ordered-set' THEN 'ordered-set'
		WHEN 'ordered map' THEN 'ordered-map'
		WHEN 'ordered-map' THEN 'ordered-map'
		WHEN 'merge sort' THEN 'merge-sort'
		WHEN 'merge-sort' THEN 'merge-sort'
		WHEN 'bucket sort' THEN 'bucket-sort'
		WHEN 'bucket-sort' THEN 'bucket-sort'
		WHEN 'counting sort' THEN 'counting-sort'
		WHEN 'counting-sort' THEN 'counting-sort'
		WHEN 'radix sort' THEN 'radix-sort'
		WHEN 'radix-sort' THEN 'radix-sort'
		WHEN 'geometry' THEN 'geometry'
		WHEN 'iterator' THEN 'iterator'
		WHEN 'randomized' THEN 'randomized'
		WHEN 'brainteaser' THEN 'brainteaser'
		WHEN 'interactive' THEN 'interactive'
		WHEN 'database' THEN 'database'
		WHEN 'shell' THEN 'shell'
		WHEN 'dynamic programming' THEN 'dynamic-programming'
		WHEN 'dynamic-programming' THEN 'dynamic-programming'
		WHEN 'memoization' THEN 'memoization'
		WHEN 'knapsack problem' THEN 'knapsack-problem'
		WHEN 'knapsack-problem' THEN 'knapsack-problem'
		WHEN '0-1 knapsack' THEN '0-1-knapsack'
		WHEN '0-1-knapsack' THEN '0-1-knapsack'
		WHEN 'complete knapsack' THEN 'complete-knapsack'
		WHEN 'complete-knapsack' THEN 'complete-knapsack'
		WHEN 'backtracking' THEN 'backtracking'
		WHEN 'divide and conquer' THEN 'divide-and-conquer'
		WHEN 'divide-and-conquer' THEN 'divide-and-conquer'
		WHEN 'union-find' THEN 'union-find'
		WHEN 'topological sort' THEN 'topological-sort'
		WHEN 'topological-sort' THEN 'topological-sort'
		WHEN 'shortest path' THEN 'shortest-path'
		WHEN 'shortest-path' THEN 'shortest-path'
		WHEN 'minimum spanning tree' THEN 'minimum-spanning-tree'
		WHEN 'minimum-spanning-tree' THEN 'minimum-spanning-tree'
		WHEN 'eulerian circuit' THEN 'eulerian-circuit'
		WHEN 'eulerian-circuit' THEN 'eulerian-circuit'
		WHEN 'biconnected component' THEN 'biconnected-component'
		WHEN 'biconnected-component' THEN 'biconnected-component'
		WHEN 'strongly connected component' THEN 'strongly-connected-component'
		WHEN 'strongly-connected-component' THEN 'strongly-connected-component'
		WHEN 'bidirectional search' THEN 'bidirectional-search'
		WHEN 'bidirectional-search' THEN 'bidirectional-search'
		WHEN 'trie' THEN 'trie'
		WHEN 'monotonic stack' THEN 'monotonic-stack'
		WHEN 'monotonic-stack' THEN 'monotonic-stack'
		WHEN 'monotonic queue' THEN 'monotonic-queue'
		WHEN 'monotonic-queue' THEN 'monotonic-queue'
		WHEN 'segment tree' THEN 'segment-tree'
		WHEN 'segment-tree' THEN 'segment-tree'
		WHEN 'binary indexed tree' THEN 'binary-indexed-tree'
		WHEN 'binary-indexed-tree' THEN 'binary-indexed-tree'
		WHEN 'quickselect' THEN 'quickselect'
		WHEN 'data stream' THEN 'data-stream'
		WHEN 'data-stream' THEN 'data-stream'
		WHEN 'sweep line' THEN 'sweep-line'
		WHEN 'sweep-line' THEN 'sweep-line'
		WHEN 'rolling hash' THEN 'rolling-hash'
		WHEN 'rolling-hash' THEN 'rolling-hash'
		WHEN 'hash function' THEN 'hash-function'
		WHEN 'hash-function' THEN 'hash-function'
		WHEN 'string matching' THEN 'string-matching'
		WHEN 'string-matching' THEN 'string-matching'
		WHEN 'suffix array' THEN 'suffix-array'
		WHEN 'suffix-array' THEN 'suffix-array'
		WHEN 'bitmask' THEN 'bitmask'
		WHEN 'number theory' THEN 'number-theory'
		WHEN 'number-theory' THEN 'number-theory'
		WHEN 'combinatorics' THEN 'combinatorics'
		WHEN 'probability and statistics' THEN 'probability-and-statistics'
		WHEN 'probability-and-statistics' THEN 'probability-and-statistics'
		WHEN 'game theory' THEN 'game-theory'
		WHEN 'game-theory' THEN 'game-theory'
		WHEN 'minimax' THEN 'minimax-algorithm'
		WHEN 'minimax-algorithm' THEN 'minimax-algorithm'
		WHEN 'meet in the middle' THEN 'meet-in-the-middle'
		WHEN 'meet-in-the-middle' THEN 'meet-in-the-middle'
		WHEN 'reservoir sampling' THEN 'reservoir-sampling'
		WHEN 'reservoir-sampling' THEN 'reservoir-sampling'
		WHEN 'rejection sampling' THEN 'rejection-sampling'
		WHEN 'rejection-sampling' THEN 'rejection-sampling'
		WHEN 'concurrency' THEN 'concurrency'
		WHEN 'heap' THEN 'heap-priority-queue'
		ELSE replace(replace(replace(replace(lower(trim(`value`)), ' ', '-'), '(', ''), ')', ''), '--', '-')
	END)
	FROM json_each(`problems`.`topic_tags`)
)
WHERE json_array_length(`topic_tags`) > 0;
